package DAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bean.ShopEntity;
import bean.ShopGoodsEntity;
import bean.ShoppingCartEntity;
import bean.ShopTempPindanEntity;

import DAO.ShopEntityDao;
import DAO.ShopGoodsEntityDao;
import DAO.ShoppingCartEntityDao;
import DAO.ShopTempPindanEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopEntityDaoConfig;
    private final DaoConfig shopGoodsEntityDaoConfig;
    private final DaoConfig shoppingCartEntityDaoConfig;
    private final DaoConfig shopTempPindanEntityDaoConfig;

    private final ShopEntityDao shopEntityDao;
    private final ShopGoodsEntityDao shopGoodsEntityDao;
    private final ShoppingCartEntityDao shoppingCartEntityDao;
    private final ShopTempPindanEntityDao shopTempPindanEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopEntityDaoConfig = daoConfigMap.get(ShopEntityDao.class).clone();
        shopEntityDaoConfig.initIdentityScope(type);

        shopGoodsEntityDaoConfig = daoConfigMap.get(ShopGoodsEntityDao.class).clone();
        shopGoodsEntityDaoConfig.initIdentityScope(type);

        shoppingCartEntityDaoConfig = daoConfigMap.get(ShoppingCartEntityDao.class).clone();
        shoppingCartEntityDaoConfig.initIdentityScope(type);

        shopTempPindanEntityDaoConfig = daoConfigMap.get(ShopTempPindanEntityDao.class).clone();
        shopTempPindanEntityDaoConfig.initIdentityScope(type);

        shopEntityDao = new ShopEntityDao(shopEntityDaoConfig, this);
        shopGoodsEntityDao = new ShopGoodsEntityDao(shopGoodsEntityDaoConfig, this);
        shoppingCartEntityDao = new ShoppingCartEntityDao(shoppingCartEntityDaoConfig, this);
        shopTempPindanEntityDao = new ShopTempPindanEntityDao(shopTempPindanEntityDaoConfig, this);

        registerDao(ShopEntity.class, shopEntityDao);
        registerDao(ShopGoodsEntity.class, shopGoodsEntityDao);
        registerDao(ShoppingCartEntity.class, shoppingCartEntityDao);
        registerDao(ShopTempPindanEntity.class, shopTempPindanEntityDao);
    }
    
    public void clear() {
        shopEntityDaoConfig.clearIdentityScope();
        shopGoodsEntityDaoConfig.clearIdentityScope();
        shoppingCartEntityDaoConfig.clearIdentityScope();
        shopTempPindanEntityDaoConfig.clearIdentityScope();
    }

    public ShopEntityDao getShopEntityDao() {
        return shopEntityDao;
    }

    public ShopGoodsEntityDao getShopGoodsEntityDao() {
        return shopGoodsEntityDao;
    }

    public ShoppingCartEntityDao getShoppingCartEntityDao() {
        return shoppingCartEntityDao;
    }

    public ShopTempPindanEntityDao getShopTempPindanEntityDao() {
        return shopTempPindanEntityDao;
    }

}
