package DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import bean.ShoppingCartEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHOPPING_CART_ENTITY".
*/
public class ShoppingCartEntityDao extends AbstractDao<ShoppingCartEntity, Long> {

    public static final String TABLENAME = "SHOPPING_CART_ENTITY";

    /**
     * Properties of entity ShoppingCartEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, long.class, "user_id", false, "USER_ID");
        public final static Property ShopGood_id = new Property(2, long.class, "shopGood_id", false, "SHOP_GOOD_ID");
        public final static Property Number = new Property(3, int.class, "number", false, "NUMBER");
    }


    public ShoppingCartEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ShoppingCartEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHOPPING_CART_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: user_id
                "\"SHOP_GOOD_ID\" INTEGER NOT NULL ," + // 2: shopGood_id
                "\"NUMBER\" INTEGER NOT NULL );"); // 3: number
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHOPPING_CART_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShoppingCartEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindLong(3, entity.getShopGood_id());
        stmt.bindLong(4, entity.getNumber());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShoppingCartEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindLong(3, entity.getShopGood_id());
        stmt.bindLong(4, entity.getNumber());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ShoppingCartEntity readEntity(Cursor cursor, int offset) {
        ShoppingCartEntity entity = new ShoppingCartEntity( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // user_id
            cursor.getLong(offset + 2), // shopGood_id
            cursor.getInt(offset + 3) // number
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShoppingCartEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getLong(offset + 1));
        entity.setShopGood_id(cursor.getLong(offset + 2));
        entity.setNumber(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ShoppingCartEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ShoppingCartEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ShoppingCartEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
