# Generated by Django 2.1 on 2018-10-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('msg_id', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('pay_url', models.TextField(default='none')),
                ('pay_type', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsSendOrder',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('original_order_id', models.CharField(max_length=32)),
                ('new_order_id', models.CharField(max_length=32)),
                ('msg_id', models.CharField(max_length=32)),
                ('sms_code_number', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(default='nick_name', max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('id_card', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=11)),
                ('card_number', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icbc_ibm_manage.User')),
            ],
        ),
        migrations.AddField(
            model_name='smssendorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icbc_ibm_manage.User'),
        ),
        migrations.AddField(
            model_name='payorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icbc_ibm_manage.User'),
        ),
    ]
